In [8]:
import matplotlib.pyplot as plt
import csv
from PIL import Image
import numpy as np
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
import argparse
import pickle

This is Testing Program. 
Note : need to change testing_directory & model_directory to correct directory 
*the model_directory included model that are output from previous "final_train_program")

run testProgram to get output.

Output of the testing program will be :
1) Accuracy of testing data 
2) Confusion matrix 
of each model



The input of testProgram(clf,rootpath) is :
1) clf can be :
"all" : will run testing data on all models
"RF" : will run testing data on Random Forest model only
"SVM" : will run testing data on SVM model only
"MLP" : will run tetsing data on MLP neural network model only 
2) rootpath : 
it's the directory of testing data, can put as "testing_directory" 

In [15]:
testing_directory = "/Users/kaiyuan/Desktop/3023Project/Test"
model_directory = '/Users/kaiyuan/Desktop/3023Project/My_model/'

In [16]:
import os
print("Folder should look like:")
print(os.listdir(testing_directory))
print()

print("Folder should look like:")
print(os.listdir(model_directory))
print()

Folder should look like:
['.DS_Store', 'model.sav', 'test1.ppm', 'test2.ppm', 'test.csv', 'test3.ppm', 'test4.ppm', 'TrafficSignsTestModel.py']

Folder should look like:
['.DS_Store', 'FinalrandomForest.pkl', 'finalsvm.pkl', 'neuralnetwork.pkl']



In [17]:
from skimage import exposure
import cv2 as cv

def readTrafficSigns(rootpath):
    '''Reads traffic sign data 
    Arguments: path to the traffic sign data, for example './TrafficSignData/Test'
    Returns:   list of images, list of corresponding labels'''
    images = [] # images
    labels = [] # corresponding labels
    prefix = rootpath + '/' # subdirectory for test
    gtFile = open(prefix + 'test'+'.csv') # annotations file
    gtReader = csv.reader(gtFile, delimiter=';') # csv parser for annotations file
    #gtReader.next() # skip header
    next(gtReader)
    # loop over all images in current annotations file
    for row in gtReader:
        img=Image.open(prefix + row[0])  # the 1th column is the filename
        # preprocesing image, make sure the images are in the same size
        img=img.crop((int(row[3]),int(row[4]),int(row[5]),int(row[6])))
        img=img.resize((32,32), Image.BICUBIC)
        img=np.array(img)
        img = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
        img=exposure.equalize_adapthist(img,clip_limit=0.1)
        images.append(img) 
        labels.append(row[7]) # the 8th column is the label
    gtFile.close()
    return images, labels



In [18]:
def loadData():
    testImages, testLabels = readTrafficSigns(testing_directory)
    print('number of testing data=', len(testLabels))
    # design the input and output for model
    X=[]
    Y=[]
    for i in range(0,len(testLabels)):
        # input X just the flattern image
        X.append(testImages[i].flatten())
        Y.append(int(testLabels[i]))
    X=np.array(X)
    Y=np.array(Y)
    return X,Y

In [21]:

def testProgram(clf,rootpath):
    
    X_pred, Y_pred = loadData()
    
    if clf =="all":
        #Load RF clf
        with open(model_directory+"FinalrandomForest.pkl", 'rb') as open_file:
            rf_clf = pickle.load(open_file)
        #Predict for RF
        Y_out = rf_clf.predict(X_pred)
        accuracy = accuracy_score(Y_pred,Y_out)
        #Output Accuracy
        print("RandomForest_Accuracy: "+str(accuracy))
        model_confusion_matrix = confusion_matrix(Y_pred,rf_clf.predict(X_pred))
        print(f"Confusion Matrix :")
        print(model_confusion_matrix)

        
        #Load SVM clf
        with open(model_directory+"finalsvm.pkl", 'rb') as open_file:
            svm_clf = pickle.load(open_file)
        #Predict for SVM
        Y_out = svm_clf.predict(X_pred)
        accuracy = accuracy_score(Y_pred,Y_out)
        #Output Accuracy
        print("SVM_Accuracy: "+str(accuracy))
        model_confusion_matrix = confusion_matrix(Y_pred,svm_clf.predict(X_pred))
        print(f"Confusion Matrix :")
        print(model_confusion_matrix)
        
        #Load MLP clf
        with open(model_directory+"neuralnetwork.pkl", 'rb') as open_file:
            mlp_clf = pickle.load(open_file)
        #Predict for mlp
        Y_out = mlp_clf.predict(X_pred)
        accuracy = accuracy_score(Y_pred,Y_out)
        #Output Accuracy
        print("NeuralNetwork_Accuracy: "+str(accuracy))
        model_confusion_matrix = confusion_matrix(Y_pred,mlp_clf.predict(X_pred))
        print(f"Confusion Matrix :")
        print(model_confusion_matrix)
        
    elif clf =="RF":
        #Load RF clf
        with open(model_directory+"FinalrandomForest.pkl", 'rb') as open_file:
            rf_clf = pickle.load(open_file)
        #Predict for RF
        Y_out = rf_clf.predict(X_pred)
        accuracy = accuracy_score(Y_pred,Y_out)
        #Output Accuracy
        print("RandomForest_Accuracy: "+str(accuracy))
        model_confusion_matrix = confusion_matrix(Y_pred,rf_clf.predict(X_pred))
        print(f"Confusion Matrix :")
        print(model_confusion_matrix)
    
    elif clf=="SVM":
        #Load SVM clf
        
        with open(model_directory+"finalsvm.pkl", 'rb') as open_file:
            svm_clf = pickle.load(open_file)
        #Predict for SVM
        Y_out = svm_clf.predict(X_pred)
        accuracy = accuracy_score(Y_pred,Y_out)
        #Output Accuracy
        print("SVM_Accuracy: "+str(accuracy))
        model_confusion_matrix = confusion_matrix(Y_pred,svm_clf.predict(X_pred))
        print(f"Confusion Matrix :")
        print(model_confusion_matrix)
    
    elif clf=="MLP":
        #Load MLP clf
        with open(model_directory+"neuralnetwork.pkl", 'rb') as open_file:
            mlp_clf = pickle.load(open_file)
        #Predict for mlp
        Y_out = mlp_clf.predict(X_pred)
        accuracy = accuracy_score(Y_pred,Y_out)
        #Output Accuracy
        print("NeuralNetwork_Accuracy: "+str(accuracy))
        model_confusion_matrix = confusion_matrix(Y_pred,mlp_clf.predict(X_pred))
        print(f"Confusion Matrix :")
        print(model_confusion_matrix)
        
    else:
        print("No such classifier found.")
    return

In [22]:
testProgram("all",testing_directory)

number of testing data= 4
RandomForest_Accuracy: 0.5
Confusion Matrix :
[[0 0 0 0]
 [0 0 0 0]
 [0 1 1 0]
 [1 0 0 1]]
SVM_Accuracy: 0.25
Confusion Matrix :
[[0 0 0 0]
 [0 0 0 0]
 [0 1 1 0]
 [1 1 0 0]]
NeuralNetwork_Accuracy: 0.25
Confusion Matrix :
[[0 0 0 0]
 [0 0 0 0]
 [0 1 1 0]
 [2 0 0 0]]
